name: ci

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      TAGS: nilsfs7/dffb.org:dev
    steps:
      - name: Set environment by branch
        id: build-args
        run: |
          echo "BUILD_TIME=$(date -u +'%Y-%m-%d %H:%M:%S')" >> "$GITHUB_ENV"
          if [[ $GITHUB_REF == 'refs/heads/main' ]]; then
              echo "set values for production image"
              
              echo "TAGS=nilsfs7/dffb.org:latest,nilsfs7/dffb.org:prod" >> "$GITHUB_ENV"
          fi
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          push: true
          file: ./Dockerfile
          tags: ${{ env.TAGS }}
